"""Daily team briefs: one original write-up per team per day, kept permanently.

Generated by jobs/daily_briefs.py (scheduled), read by the site and the tweet bot.
"""
import json
import os
from datetime import datetime
from zoneinfo import ZoneInfo

from lib import store
from lib.articles import collect_ranked_articles
from lib.search import tavily_search
from lib.teams import TEAMS, TEAM_SLUGS
from utils.article_filter import get_source_name_from_url

EASTERN = ZoneInfo("America/New_York")
_MAX_SOURCES = 16


def local_today() -> str:
    """Today's date in Philadelphia, YYYY-MM-DD."""
    return datetime.now(EASTERN).date().isoformat()


def _date_score(day: str) -> int:
    return int(day.replace("-", ""))


# ---------------------------------------------------------------------------
# Storage
# ---------------------------------------------------------------------------

def save_brief(brief: dict) -> None:
    r = store.client()
    team, day = brief["team"], brief["date"]
    r.set(store.key("brief", team, day), json.dumps(brief))
    r.zadd(store.key("briefs", team), {day: _date_score(day)})
    r.zadd(store.key("briefs", "all"), {f"{team}:{day}": _date_score(day)})


def get_brief(team: str, day: str) -> dict | None:
    raw = store.client().get(store.key("brief", team, day))
    return json.loads(raw) if raw else None


def brief_dates(team: str, limit: int = -1) -> list[str]:
    """Dates with a brief for this team, newest first."""
    end = -1 if limit < 0 else limit - 1
    return list(store.client().zrevrange(store.key("briefs", team), 0, end))


def latest_brief(team: str) -> dict | None:
    dates = brief_dates(team, limit=1)
    return get_brief(team, dates[0]) if dates else None


def recent_briefs(limit: int = 40) -> list[tuple[str, str]]:
    """(team, date) pairs across all teams, newest first."""
    members = store.client().zrevrange(store.key("briefs", "all"), 0, limit - 1)
    return [tuple(m.split(":", 1)) for m in members]


# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------

def _gather_sources(team: str) -> list[dict]:
    t = TEAMS[team]
    sources = []
    seen = set()
    for a in collect_ranked_articles(team, max_articles=12):
        if a["title"] and a["url"] not in seen:
            seen.add(a["url"])
            sources.append({"title": a["title"], "url": a["url"], "source": a["source"],
                            "snippet": a["description"][:300]})
    for r in tavily_search(f"{t['full_name']} news", topic="news", max_results=8, time_range="day"):
        url = (r.get("url") or "").strip()
        title = (r.get("title") or "").strip()
        if url.startswith("http") and title and url not in seen:
            seen.add(url)
            sources.append({"title": title, "url": url, "source": get_source_name_from_url(url),
                            "snippet": (r.get("content") or "")[:300].strip()})
    return sources[:_MAX_SOURCES]


_SYSTEM = """You are the editor of Philly Sport Daily, writing the daily {team} brief for Philadelphia fans.

Write an original brief that tells a fan what matters today and why, using ONLY the numbered sources provided.
- Synthesize: group related stories into 2 to 4 sections, explain the stakes, connect storylines. Do not just list headlines.
- Never invent facts, scores, stats, quotes, injuries, trades or dates. If a detail is not in the sources, leave it out.
- Attribute notable claims to the outlet (e.g. "per PhillyVoice"). Rumors must be labeled as rumors.
- Voice: knowledgeable local fan who respects the reader. Plain, specific, a little personality. No hype words, no em dashes, no "it's not just X, it's Y".
- Total length 250 to 450 words. If the news is thin, write less rather than padding.
- Today's date is {today}. Do not describe the season phase unless the sources do.

Return JSON with exactly these keys:
{{"headline": "specific, under 90 characters, no clickbait",
  "summary": "2 to 3 sentences, the most important takeaways",
  "sections": [{{"heading": "short", "body": "1 to 3 paragraphs separated by blank lines", "sources": [source numbers used]}}]}}"""


def generate_brief(team: str, day: str | None = None) -> dict | None:
    """Write today's brief for a team. Returns the brief dict, or None if there's nothing to write about."""
    from openai import OpenAI

    day = day or local_today()
    sources = _gather_sources(team)
    if len(sources) < 3:
        print(f"{team}: only {len(sources)} sources, skipping brief")
        return None

    numbered = "\n\n".join(
        f"[{i}] {s['title']} ({s['source']})\n{s['snippet']}" for i, s in enumerate(sources, 1)
    )
    model = os.environ.get("BRIEF_MODEL", "gpt-5.4-mini")
    resp = OpenAI().chat.completions.create(
        model=model,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": _SYSTEM.format(team=TEAMS[team]["full_name"], today=day)},
            {"role": "user", "content": f"Sources:\n\n{numbered}"},
        ],
    )
    data = json.loads(resp.choices[0].message.content or "{}")

    sections = []
    used = []
    for sec in data.get("sections") or []:
        body = (sec.get("body") or "").strip()
        if not body:
            continue
        refs = []
        for n in sec.get("sources") or []:
            if isinstance(n, int) and 1 <= n <= len(sources):
                s = sources[n - 1]
                ref = {"title": s["title"], "url": s["url"], "source": s["source"]}
                refs.append(ref)
                if ref not in used:
                    used.append(ref)
        sections.append({
            "heading": (sec.get("heading") or "").strip(),
            "paragraphs": [p.strip() for p in body.split("\n\n") if p.strip()],
            "sources": refs,
        })
    headline = (data.get("headline") or "").strip()
    summary = (data.get("summary") or "").strip()
    if not headline or not summary or not sections:
        print(f"{team}: model returned an incomplete brief, skipping")
        return None

    return {
        "team": team,
        "date": day,
        "headline": headline,
        "summary": summary,
        "sections": sections,
        "sources": used,
        "generated_at": datetime.now(EASTERN).isoformat(timespec="minutes"),
        "model": model,
    }


def generate_all(day: str | None = None) -> list[dict]:
    day = day or local_today()
    written = []
    for team in TEAM_SLUGS:
        try:
            brief = generate_brief(team, day)
        except Exception as e:
            print(f"{team}: brief generation failed: {e}")
            continue
        if brief:
            save_brief(brief)
            written.append(brief)
            print(f"{team}: saved brief '{brief['headline']}'")
    return written
